### ISSUE TITLE
Buscar un Template 

### ISSUE THREAD

**Issue by ludstuen90** [ludstuen90/judithmdb#1]
Decidir cual template usar para el sitio. Hay varios ejemplos en https://wordpress.com/themes/, y dado que estamos usando lightsail, podríamos customizar cualquier template que lo permita. 

Secciones del sitio: 
Página principal
Menú con 3 opciones: 
- About
- Portfolio
- Blog

- [x] Escoger un template 
- [x] Hacer un issue en github para todas las secciones que necesitarán texto 
- [ ] Identificar como queremos customizar el theme, y hacer issues

**Comment by judithmdb** [comment]
Estoy terminando de definir el estilo, el layout está decidido. Esta semana hacemos un primer cierre de este issue.
