### ISSUE TITLE
Agregar página de credits (Iconitos)

### ISSUE THREAD

**Issue by ludstuen90** [ludstuen90/judithmdb#24]
Agregar página dando credit a los iconitos

**Comment by ludstuen90** [comment]
Listo, pero dejo el ticket a vos, por si querés cambiar el contenido 
http://52.201.16.250/thanks/

**Comment by judithmdb** [comment]
Dale cambiémoslo a 
Want to use the icons seen in this site? You could, but make sure you cite them.
They're free to download. Made by Freepik from www.flaticon.com

**Comment by ludstuen90** [comment]
@judithmdb  acutalizado y deployado en el sitio ! listo para revisar
