### ISSUE TITLE
new item or post

### ISSUE THREAD

**Issue by judithmdb** [ludstuen90/judithmdb#38]
los elementos deberían ir newest on top, from left to right. Oldest on the bottom.
Y no cambiar lo que estoy haciendo cuando se implemente :') or i might die.

**Comment by ludstuen90** [comment]
Como hablamos por whatsapp, agregamos un campo de "orden", que podés usar para poner todos los items en orden: el item con el número más grande va a aparecer primero

**Comment by judithmdb** [comment]
No sé yo lo cerré tipo confianza sin ver.
