### ISSUE TITLE
mail address

### ISSUE THREAD

**Issue by judithmdb** [ludstuen90/judithmdb#41]
me olvidé del contacto por mail. te paso un iconito en Soporte Visual por si lo querés agregar junto con las otras redes. Espero que no me odies.

**Comment by judithmdb** [comment]
bueno tmb te lo dejo acá así no abrís drive para nada https://www.flaticon.com/free-icon/gmail_2991143

**Comment by ludstuen90** [comment]
Dale, no hay drama -- que te parece lo agregamos solo en Desktop?? Quedamos medio corto de espacio en mobile 
![image](https://user-images.githubusercontent.com/6817579/93720969-2c318b80-fb63-11ea-8fe7-e3c2937a2efd.png)

**Comment by judithmdb** [comment]
OK!
